config/routes.rb
Rails.application.routes.draw do
  root 'logs#index'

  devise_for :users

  resources :logs do
    resources :comments
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :log
  belongs_to :user
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def create
    @log = Log.find(params[:log_id])
    @comment = @log.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to logs_path(@logs), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    @comment.destroy
    redirect_to request.referer, notice: 'Comment was successfully destroyed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :log_id, :user_id)
  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if @user =current_user
      @logs = Log.all
    else
      @logs = Log.where(:is_hidden => true)
    end

  end

  def new
    @log = current_user.logs.build
  end

  def create
    @log = current_user.logs.build(log_params)

    if @log.save
      redirect_to logs_path
    else
      render :new
    end
  end

  def show
    @log = Log.find(params[:id])
  end

  def edit
    @log = Log.find(params[:id])
  end

  def update
    @log = Log.find(params[:id])

    if @log.update(log_params)
      redirect_to logs_path
    else
      render :edit
    end
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path, notice: "Deleted!"
  end

  private

  def log_params
    params.require(:log).permit(:title, :body, :is_hidden)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
<div class="comments_wrapper clearfix">
    <div class="btn-group pull-right">
        <% if comment.user == current_user %>
        <%= link_to '删除', log_comment_path(comment.log, comment), method: :delete, data: { confirm: 'Are you sure?' },
          class: "btn-sm btn-default" %>
        <% end %>
    </div>

    <div class="pull-left">
        <%= comment.user.email %>:<%= comment.body %></p>
    </div>

</div>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">
        <br>Design by
        Lucas</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<div class="navbar-inner">
    <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "LOG", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to '新增 Log', new_log_path %></li>
                <% if user_signed_in? %>
                <li><%= link_to '个人信息', edit_user_registration_path %></li>
                <li><%= link_to '退出登录', destroy_user_session_path, :method=> :delete %></li>
            </ul>
        <% else %>
            <ul class="nav navbar-nav pull-right">
                <li><%= link_to '注册', new_user_registration_path %></li>
                <li><%= link_to '登录', new_user_session_path %></li>
            </ul>
            <% end %>
        </nav>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Log</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>
    <body>
        <header class="navbar navbar-default" role="navigation">
            <%= render "common/navbar" %>
        </header>

        <div id="main_content" class="container">
            <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{name}")%>
            <% end %>

            <div id="content" class="col-md-9 center-block">
                <%= yield %>
            </div>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/logs/edit.html.erb
<h2>Edit</h2>

<%= simple_form_for(@log) do |f| %>

<div class="form-group">
    <%= f.label :标题 %><br>
    <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :内容 %><br>
    <%= f.text_field :body, class: "form-control" %>
</div>

<div class="group">
  <%= f.check_box :is_hidden%>发布
</div>


<div class="group">
  <%= f.submit "Submit", class: "btn btn-primary" %>
</div>

<% end %>

app/views/logs/index.html.erb
<% @logs.each do |log| %>
<div class="link row clearfix">

	<table>
		<tbody>
			<ul>
				<h2><%= link_to log.title, log %></h2>
				<br>
				<p><%= log.body %></p>
				<br>
				<h5>
					<%= log.comments.count %>
					Commments
				</h5>
			</ul>

			<%= simple_form_for [Log, Comment.new] do |f| %>

			<div class="leftmargin">

				<div class="pull-right">
					<%= link_to '去评论', log, class: "btn btn-sm  btn-danger" %>
				</div>
				<br><br>

				<div class="comments">
					<%= render :partial => log.comments %>
				</div>
			</div>
		</table>
	</div>

	<% end %>
	<% end %>

app/views/logs/new.html.erb
<h2>New</h2>

<%= simple_form_for(@log) do |f| %>

<div class="form-group">
    <%= f.label :标题 %><br>
    <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :内容 %><br>
    <%= f.text_field :body, class: "form-control" %>
</div>

<div class="group">
  <%= f.check_box :is_hidden%>发布
</div>

<div class="group">
  <%= f.submit "Submit", class: "btn btn-primary" %>
</div>

<% end %>

app/views/logs/show.html.erb
<h1>XXX的博客</h1>
<div class="page-header">
    <h3>
        <%= @log.title %>
    </h3>
</div>
<% if @log.user == current_user %>
<div class="btn-group pull-right">
    <%= link_to 'Edit', edit_log_path(@log), class: "btn btn-default" %>
    <%= link_to 'Destroy', @log, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
</div>
<h4>
    
    <%= @log.body %>
    </h4>

<% end %>

<h3 class="comment_title">
  <%= @log.comments.count %>
  Commments
</h3>

<div class="comments">
  <%= render :partial => @log.comments %>
</div>
<%= simple_form_for [@log, Comment.new] do |f| %>
<div class="field">
  <%= f.text_area :body, class: "form-control" %>
</div>
<br>
<%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>